apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-controller
  labels:
    app: mcp-controller
    component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-controller
      component: controller
  template:
    metadata:
      labels:
        app: mcp-controller
        component: controller
    spec:
      serviceAccountName: mcp-controller
      containers:
        - name: mcp-controller
          image: quay.io/rhn_support_memodi/mcp-controller:2165251-20260403-160133
          imagePullPolicy: Always
          command:
            - ./mcp_controller
            - --log-level=0 # info level
          env:
            - name: RELATED_IMAGE_ROUTER_BROKER
              value: quay.io/rhn_support_memodi/mcp-gateway:dc6cc7c-20260326-132316
            - name: RELATED_IMAGE_CONSOLE_PLUGIN
              value: quay.io/rhn_support_memodi/mcp-gateway-console-plugin:d0bbf9e-20260406-162459
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
            - name: metrics
              containerPort: 8082
              protocol: TCP
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
